# Generated by Django 4.1.6 on 2023-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imgfile',
            field=models.ImageField(upload_to='myapp/static'),
        ),
    ]
