# Generated by Django 4.1.6 on 2023-02-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_imagemodel_imgfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='shpregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_Num', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
                ('Shop_id', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
