# Generated by Django 4.1.6 on 2023-02-14 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_ufilemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uregmodel',
            old_name='place',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='uregmodel',
            old_name='user_id',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='ufilemodel',
            name='imgfile',
            field=models.ImageField(upload_to='myapp/static'),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
