# Generated by Django 4.1.6 on 2023-02-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_place_uregmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uregmodel',
            old_name='name',
            new_name='username',
        ),
    ]
