# Generated by Django 4.1.6 on 2023-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='whislist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdctname', models.CharField(max_length=20)),
                ('prdctprice', models.IntegerField()),
                ('imgfile', models.ImageField(upload_to='')),
            ],
        ),
    ]
