# Generated by Django 4.1.6 on 2023-02-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_whislist'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdctname', models.CharField(max_length=20)),
                ('prdctprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
