# Generated by Django 4.1.6 on 2023-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('cardexpiry', models.DateTimeField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
